sites:
  # - name: Ministry of Justice (Arabic)
  #   url: https://www.moj.gov.ae/ar/home.aspx
  #   last_crawled: 

  - name: Ministry of Justice (English)
    url: https://www.moj.gov.ae/en/home.aspx
    last_crawled: 

  # - name: UAE Official Gazette
  #   url: https://elaws.moj.gov.ae
  #   last_crawled:
