sites:
- last_crawled: 
  name: Ministry of Justice (English)
  url: https://www.moj.gov.ae/assets/2025/Federal Law No 10 2014 On the Amendment of Certain Provisions of the Civil Procedures Law issued by virtue of Federal Law No. 11 of 1992.pdf.aspx
